[build]
  base = "client"        # run builds from /client
  command = "npm run build"
  publish = "build"      # CRA outputs to /client/build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200